create_clock -period 20.000 -name sys_clk [get_ports sys_clk]
# 声明 clk_out1_pll_ip 和 sys_clk 属于异步时钟组
set_clock_groups -asynchronous -group clk_out1_pll_ip -group sys_clk

set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[0]}]
set_property PACKAGE_PIN T15 [get_ports {adc_data[7]}]
set_property PACKAGE_PIN T14 [get_ports {adc_data[6]}]
set_property PACKAGE_PIN V13 [get_ports {adc_data[5]}]
set_property PACKAGE_PIN U13 [get_ports {adc_data[4]}]
set_property PACKAGE_PIN U12 [get_ports {adc_data[3]}]
set_property PACKAGE_PIN T12 [get_ports {adc_data[2]}]
set_property PACKAGE_PIN T10 [get_ports {adc_data[1]}]
set_property PACKAGE_PIN T11 [get_ports {adc_data[0]}]
set_property PACKAGE_PIN V18 [get_ports ad_clk]
set_property PACKAGE_PIN N18 [get_ports sys_clk]
set_property PACKAGE_PIN G19 [get_ports sys_rst_n]
set_property PACKAGE_PIN W19 [get_ports da_clk]
set_property PACKAGE_PIN T16 [get_ports {dac_data[7]}]
set_property PACKAGE_PIN U17 [get_ports {dac_data[6]}]
set_property PACKAGE_PIN P15 [get_ports {dac_data[5]}]
set_property PACKAGE_PIN P16 [get_ports {dac_data[4]}]
set_property PACKAGE_PIN P14 [get_ports {dac_data[3]}]
set_property PACKAGE_PIN R14 [get_ports {dac_data[2]}]
set_property PACKAGE_PIN V16 [get_ports {dac_data[1]}]
set_property PACKAGE_PIN W16 [get_ports {dac_data[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports ad_clk]
set_property IOSTANDARD LVCMOS33 [get_ports da_clk]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports sys_rst_n]

set_property IOSTANDARD LVCMOS33 [get_ports fifo_empty]
set_property IOSTANDARD LVCMOS33 [get_ports rd_en]
set_property PACKAGE_PIN K16 [get_ports fifo_empty]
set_property PACKAGE_PIN H15 [get_ports rd_en]
set_property IOSTANDARD LVCMOS33 [get_ports fifo_full]
set_property IOSTANDARD LVCMOS33 [get_ports wr_en]
set_property PACKAGE_PIN J16 [get_ports fifo_full]
set_property PACKAGE_PIN G20 [get_ports wr_en]
# set_property IOSTANDARD LVCMOS33 [get_ports wr_clk]
set_property PACKAGE_PIN K14 [get_ports reading]
set_property PACKAGE_PIN J14 [get_ports writing]

set_property IOSTANDARD LVCMOS33 [get_ports reading]
set_property IOSTANDARD LVCMOS33 [get_ports writing]


set_property PACKAGE_PIN J14 [get_ports fifo_in_ready]
set_property IOSTANDARD LVCMOS33 [get_ports fifo_in_ready]

set_property PACKAGE_PIN K16 [get_ports music]
set_property PACKAGE_PIN J14 [get_ports busy]
set_property PACKAGE_PIN J16 [get_ports voice]
set_property IOSTANDARD LVCMOS33 [get_ports busy]
set_property IOSTANDARD LVCMOS33 [get_ports music]
set_property IOSTANDARD LVCMOS33 [get_ports voice]

set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_I_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_I_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_I_0[0]}]
set_property PACKAGE_PIN K16 [get_ports {GPIO_I_0[2]}]
set_property PACKAGE_PIN J16 [get_ports {GPIO_I_0[1]}]
set_property PACKAGE_PIN J14 [get_ports {GPIO_I_0[0]}]

set_property PACKAGE_PIN K14 [get_ports max]
set_property IOSTANDARD LVCMOS33 [get_ports max]

set_property IOSTANDARD LVCMOS33 [get_ports {index[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {index[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {index[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {index[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {index[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {index[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {index[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {index[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {index[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {index[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {index[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {index[0]}]
