# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/FPGA/work_space/AD_DA_tran/AD_DA_tran.srcs/sources_1/ip/pll_ip/pll_ip.xci
# IP: The module: 'pll_ip' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/FPGA/work_space/AD_DA_tran/AD_DA_tran.srcs/sources_1/ip/pll_ip/pll_ip_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_ip'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/FPGA/work_space/AD_DA_tran/AD_DA_tran.srcs/sources_1/ip/pll_ip/pll_ip.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_ip'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/FPGA/work_space/AD_DA_tran/AD_DA_tran.srcs/sources_1/ip/pll_ip/pll_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_ip'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: F:/FPGA/work_space/AD_DA_tran/AD_DA_tran.srcs/sources_1/ip/pll_ip/pll_ip.xci
# IP: The module: 'pll_ip' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/FPGA/work_space/AD_DA_tran/AD_DA_tran.srcs/sources_1/ip/pll_ip/pll_ip_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_ip'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/FPGA/work_space/AD_DA_tran/AD_DA_tran.srcs/sources_1/ip/pll_ip/pll_ip.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_ip'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/FPGA/work_space/AD_DA_tran/AD_DA_tran.srcs/sources_1/ip/pll_ip/pll_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_ip'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
