# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/adda.xdc

# Block Designs: bd/zynq_a9/zynq_a9.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_a9 || ORIG_REF_NAME==zynq_a9} -quiet] -quiet

# IP: bd/zynq_a9/ip/zynq_a9_processing_system7_0_0/zynq_a9_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_a9_processing_system7_0_0 || ORIG_REF_NAME==zynq_a9_processing_system7_0_0} -quiet] -quiet

# XDC: bd/zynq_a9/ip/zynq_a9_processing_system7_0_0/zynq_a9_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_a9_processing_system7_0_0 || ORIG_REF_NAME==zynq_a9_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/zynq_a9/zynq_a9_ooc.xdc
