# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param tcl.collectionResultDisplayLimit 0
set_param xicom.use_bs_reader 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg400-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/FPGA/work_space/AD_DA_tran/AD_DA_tran.cache/wt [current_project]
set_property parent.project_path F:/FPGA/work_space/AD_DA_tran/AD_DA_tran.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo f:/FPGA/work_space/AD_DA_tran/AD_DA_tran.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  F:/FPGA/work_space/AD_DA_tran/AD_DA_tran.srcs/sources_1/new/AD.v
  F:/FPGA/work_space/AD_DA_tran/AD_DA_tran.srcs/sources_1/new/AD_DA_tran.v
  F:/FPGA/work_space/AD_DA_tran/AD_DA_tran.srcs/sources_1/new/DA.v
  F:/FPGA/work_space/AD_DA_tran/AD_DA_tran.srcs/sources_1/new/TOP.v
  F:/FPGA/work_space/AD_DA_tran/AD_DA_tran.srcs/sources_1/new/ad_fifo.v
  F:/FPGA/work_space/AD_DA_tran/AD_DA_tran.srcs/sources_1/new/clk_2k.v
  F:/FPGA/work_space/AD_DA_tran/AD_DA_tran.srcs/sources_1/new/clock_div.v
  F:/FPGA/work_space/AD_DA_tran/AD_DA_tran.srcs/sources_1/new/fft_fifo.v
  F:/FPGA/work_space/AD_DA_tran/AD_DA_tran.srcs/sources_1/imports/new/fft_t.v
  F:/FPGA/work_space/AD_DA_tran/AD_DA_tran.srcs/sources_1/new/fifo_FFT.v
  F:/FPGA/work_space/AD_DA_tran/AD_DA_tran.srcs/sources_1/new/multiple_power.v
  F:/FPGA/work_space/AD_DA_tran/AD_DA_tran.srcs/sources_1/new/peak_classify.v
  F:/FPGA/work_space/AD_DA_tran/AD_DA_tran.srcs/sources_1/new/peak_find.v
  F:/FPGA/work_space/AD_DA_tran/AD_DA_tran.srcs/sources_1/bd/zynq_a9/hdl/zynq_a9_wrapper.v
  F:/FPGA/work_space/AD_DA_tran/AD_DA_tran.srcs/sources_1/new/FFT_OUT.v
}
add_files F:/FPGA/work_space/AD_DA_tran/AD_DA_tran.srcs/sources_1/bd/zynq_a9/zynq_a9.bd
set_property used_in_implementation false [get_files -all f:/FPGA/work_space/AD_DA_tran/AD_DA_tran.srcs/sources_1/bd/zynq_a9/ip/zynq_a9_processing_system7_0_0/zynq_a9_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all F:/FPGA/work_space/AD_DA_tran/AD_DA_tran.srcs/sources_1/bd/zynq_a9/zynq_a9_ooc.xdc]

read_ip -quiet F:/FPGA/work_space/AD_DA_tran/AD_DA_tran.srcs/sources_1/ip/pll_ip/pll_ip.xci
set_property used_in_implementation false [get_files -all f:/FPGA/work_space/AD_DA_tran/AD_DA_tran.srcs/sources_1/ip/pll_ip/pll_ip_board.xdc]
set_property used_in_implementation false [get_files -all f:/FPGA/work_space/AD_DA_tran/AD_DA_tran.srcs/sources_1/ip/pll_ip/pll_ip.xdc]
set_property used_in_implementation false [get_files -all f:/FPGA/work_space/AD_DA_tran/AD_DA_tran.srcs/sources_1/ip/pll_ip/pll_ip_ooc.xdc]

read_ip -quiet F:/FPGA/work_space/AD_DA_tran/AD_DA_tran.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci
set_property used_in_implementation false [get_files -all f:/FPGA/work_space/AD_DA_tran/AD_DA_tran.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xdc]
set_property used_in_implementation false [get_files -all f:/FPGA/work_space/AD_DA_tran/AD_DA_tran.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0_ooc.xdc]

read_ip -quiet F:/FPGA/work_space/AD_DA_tran/AD_DA_tran.srcs/sources_1/ip/xfft_0/xfft_0.xci
set_property used_in_implementation false [get_files -all f:/FPGA/work_space/AD_DA_tran/AD_DA_tran.srcs/sources_1/ip/xfft_0/xfft_0_ooc.xdc]

read_ip -quiet F:/FPGA/work_space/AD_DA_tran/AD_DA_tran.srcs/sources_1/ip/ila_2/ila_2.xci
set_property used_in_synthesis false [get_files -all f:/FPGA/work_space/AD_DA_tran/AD_DA_tran.srcs/sources_1/ip/ila_2/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all f:/FPGA/work_space/AD_DA_tran/AD_DA_tran.srcs/sources_1/ip/ila_2/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all f:/FPGA/work_space/AD_DA_tran/AD_DA_tran.srcs/sources_1/ip/ila_2/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all f:/FPGA/work_space/AD_DA_tran/AD_DA_tran.srcs/sources_1/ip/ila_2/ila_2_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/FPGA/work_space/AD_DA_tran/AD_DA_tran.srcs/constrs_1/new/adda.xdc
set_property used_in_implementation false [get_files F:/FPGA/work_space/AD_DA_tran/AD_DA_tran.srcs/constrs_1/new/adda.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top FFT_OUT -part xc7z020clg400-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef FFT_OUT.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file FFT_OUT_utilization_synth.rpt -pb FFT_OUT_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
