# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "E:/202511FPGA/Audio_Analyzer_FFT/.Xil/Vivado-28364-Peaceinlife/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7z020clg400-2
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include e:/202511FPGA/Audio_Analyzer_FFT/Audio_Analyzer_FFT.srcs/sources_1/bd/zynq_a9/ipshared/70cf/hdl {
      F:/FPGA/Vivado18.3/Vivado/2018.3/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      F:/FPGA/Vivado18.3/Vivado/2018.3/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include e:/202511FPGA/Audio_Analyzer_FFT/Audio_Analyzer_FFT.srcs/sources_1/bd/zynq_a9/ipshared/70cf/hdl {
      E:/202511FPGA/Audio_Analyzer_FFT/.Xil/Vivado-28364-Peaceinlife/realtime/pll_ip_stub.v
      E:/202511FPGA/Audio_Analyzer_FFT/.Xil/Vivado-28364-Peaceinlife/realtime/fifo_generator_0_stub.v
      E:/202511FPGA/Audio_Analyzer_FFT/.Xil/Vivado-28364-Peaceinlife/realtime/xfft_0_stub.v
      E:/202511FPGA/Audio_Analyzer_FFT/.Xil/Vivado-28364-Peaceinlife/realtime/ila_2_stub.v
      e:/202511FPGA/Audio_Analyzer_FFT/Audio_Analyzer_FFT.srcs/sources_1/bd/zynq_a9/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_aw_atc.v
      e:/202511FPGA/Audio_Analyzer_FFT/Audio_Analyzer_FFT.srcs/sources_1/bd/zynq_a9/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_b_atc.v
      e:/202511FPGA/Audio_Analyzer_FFT/Audio_Analyzer_FFT.srcs/sources_1/bd/zynq_a9/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_w_atc.v
      e:/202511FPGA/Audio_Analyzer_FFT/Audio_Analyzer_FFT.srcs/sources_1/bd/zynq_a9/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_atc.v
      e:/202511FPGA/Audio_Analyzer_FFT/Audio_Analyzer_FFT.srcs/sources_1/bd/zynq_a9/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_trace_buffer.v
      e:/202511FPGA/Audio_Analyzer_FFT/Audio_Analyzer_FFT.srcs/sources_1/bd/zynq_a9/ip/zynq_a9_processing_system7_0_0/hdl/verilog/processing_system7_v5_5_processing_system7.v
      e:/202511FPGA/Audio_Analyzer_FFT/Audio_Analyzer_FFT.srcs/sources_1/bd/zynq_a9/ip/zynq_a9_processing_system7_0_0/synth/zynq_a9_processing_system7_0_0.v
      E:/202511FPGA/Audio_Analyzer_FFT/Audio_Analyzer_FFT.srcs/sources_1/bd/zynq_a9/synth/zynq_a9.v
      E:/202511FPGA/Audio_Analyzer_FFT/Audio_Analyzer_FFT.srcs/sources_1/new/AD.v
      E:/202511FPGA/Audio_Analyzer_FFT/Audio_Analyzer_FFT.srcs/sources_1/new/AD_DA_tran.v
      E:/202511FPGA/Audio_Analyzer_FFT/Audio_Analyzer_FFT.srcs/sources_1/new/DA.v
      E:/202511FPGA/Audio_Analyzer_FFT/Audio_Analyzer_FFT.srcs/sources_1/new/TOP.v
      E:/202511FPGA/Audio_Analyzer_FFT/Audio_Analyzer_FFT.srcs/sources_1/new/ad_fifo.v
      E:/202511FPGA/Audio_Analyzer_FFT/Audio_Analyzer_FFT.srcs/sources_1/new/clk_2k.v
      E:/202511FPGA/Audio_Analyzer_FFT/Audio_Analyzer_FFT.srcs/sources_1/new/clock_div.v
      E:/202511FPGA/Audio_Analyzer_FFT/Audio_Analyzer_FFT.srcs/sources_1/new/fft_fifo.v
      E:/202511FPGA/Audio_Analyzer_FFT/Audio_Analyzer_FFT.srcs/sources_1/imports/new/fft_t.v
      E:/202511FPGA/Audio_Analyzer_FFT/Audio_Analyzer_FFT.srcs/sources_1/new/fifo_FFT.v
      E:/202511FPGA/Audio_Analyzer_FFT/Audio_Analyzer_FFT.srcs/sources_1/new/multiple_power.v
      E:/202511FPGA/Audio_Analyzer_FFT/Audio_Analyzer_FFT.srcs/sources_1/new/peak_classify.v
      E:/202511FPGA/Audio_Analyzer_FFT/Audio_Analyzer_FFT.srcs/sources_1/new/peak_find.v
      E:/202511FPGA/Audio_Analyzer_FFT/Audio_Analyzer_FFT.srcs/sources_1/bd/zynq_a9/hdl/zynq_a9_wrapper.v
      E:/202511FPGA/Audio_Analyzer_FFT/Audio_Analyzer_FFT.srcs/sources_1/new/FFT_OUT.v
    }
      rt::read_vhdl -lib xpm F:/FPGA/Vivado18.3/Vivado/2018.3/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top FFT_OUT
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "E:/202511FPGA/Audio_Analyzer_FFT/.Xil/Vivado-28364-Peaceinlife/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
